// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.19.6
// source: dto.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "orderspharmacydto";

/** Equivalente a: pub struct DtoUpdateMedications */
export interface DtoUpdateMedications {
  idAgent: string;
  idPharmacy: string;
  /** 'repeated' es el equivalente al Vec<> de Rust */
  medications: MedicationProto[];
}

export interface MedicationProto {
  brand: string;
  /** Mapea a activeIngredient */
  activeIngredient: string;
  dosage: string;
  /** Se mantiene como string según tu struct */
  tablets: string;
  /** Mapea a barCode */
  barCode: string;
  name: string;
  image: string;
  category: string;
  subcategory: string;
  /** f64 en Rust es double en Proto */
  price: number;
  quantity: number;
  stock: number;
  description: string;
  controlled: boolean;
  vat: number;
  antibiotic: boolean;
  minimum: number;
}

export interface OrderContactAndItems {
  orderId: string;
  pharmacyId: string;
  clientName: string;
  clientAddress: string;
  clientIdNumber: string;
  clientPhone: string;
  clientEmail: string;
  items: OrderItem[];
}

/** Ítem en la orden (medicamento y cantidad) */
export interface OrderItem {
  barcode: string;
  quantity: number;
}

function createBaseDtoUpdateMedications(): DtoUpdateMedications {
  return { idAgent: "", idPharmacy: "", medications: [] };
}

export const DtoUpdateMedications: MessageFns<DtoUpdateMedications> = {
  encode(message: DtoUpdateMedications, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idAgent !== "") {
      writer.uint32(10).string(message.idAgent);
    }
    if (message.idPharmacy !== "") {
      writer.uint32(18).string(message.idPharmacy);
    }
    for (const v of message.medications) {
      MedicationProto.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DtoUpdateMedications {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDtoUpdateMedications();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.idAgent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.idPharmacy = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.medications.push(MedicationProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DtoUpdateMedications {
    return {
      idAgent: isSet(object.idAgent)
        ? globalThis.String(object.idAgent)
        : isSet(object.id_agent)
        ? globalThis.String(object.id_agent)
        : "",
      idPharmacy: isSet(object.idPharmacy)
        ? globalThis.String(object.idPharmacy)
        : isSet(object.id_pharmacy)
        ? globalThis.String(object.id_pharmacy)
        : "",
      medications: globalThis.Array.isArray(object?.medications)
        ? object.medications.map((e: any) => MedicationProto.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DtoUpdateMedications): unknown {
    const obj: any = {};
    if (message.idAgent !== "") {
      obj.idAgent = message.idAgent;
    }
    if (message.idPharmacy !== "") {
      obj.idPharmacy = message.idPharmacy;
    }
    if (message.medications?.length) {
      obj.medications = message.medications.map((e) => MedicationProto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DtoUpdateMedications>, I>>(base?: I): DtoUpdateMedications {
    return DtoUpdateMedications.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DtoUpdateMedications>, I>>(object: I): DtoUpdateMedications {
    const message = createBaseDtoUpdateMedications();
    message.idAgent = object.idAgent ?? "";
    message.idPharmacy = object.idPharmacy ?? "";
    message.medications = object.medications?.map((e) => MedicationProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMedicationProto(): MedicationProto {
  return {
    brand: "",
    activeIngredient: "",
    dosage: "",
    tablets: "",
    barCode: "",
    name: "",
    image: "",
    category: "",
    subcategory: "",
    price: 0,
    quantity: 0,
    stock: 0,
    description: "",
    controlled: false,
    vat: 0,
    antibiotic: false,
    minimum: 0,
  };
}

export const MedicationProto: MessageFns<MedicationProto> = {
  encode(message: MedicationProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.brand !== "") {
      writer.uint32(10).string(message.brand);
    }
    if (message.activeIngredient !== "") {
      writer.uint32(18).string(message.activeIngredient);
    }
    if (message.dosage !== "") {
      writer.uint32(26).string(message.dosage);
    }
    if (message.tablets !== "") {
      writer.uint32(34).string(message.tablets);
    }
    if (message.barCode !== "") {
      writer.uint32(42).string(message.barCode);
    }
    if (message.name !== "") {
      writer.uint32(50).string(message.name);
    }
    if (message.image !== "") {
      writer.uint32(58).string(message.image);
    }
    if (message.category !== "") {
      writer.uint32(66).string(message.category);
    }
    if (message.subcategory !== "") {
      writer.uint32(74).string(message.subcategory);
    }
    if (message.price !== 0) {
      writer.uint32(81).double(message.price);
    }
    if (message.quantity !== 0) {
      writer.uint32(89).double(message.quantity);
    }
    if (message.stock !== 0) {
      writer.uint32(97).double(message.stock);
    }
    if (message.description !== "") {
      writer.uint32(106).string(message.description);
    }
    if (message.controlled !== false) {
      writer.uint32(112).bool(message.controlled);
    }
    if (message.vat !== 0) {
      writer.uint32(121).double(message.vat);
    }
    if (message.antibiotic !== false) {
      writer.uint32(128).bool(message.antibiotic);
    }
    if (message.minimum !== 0) {
      writer.uint32(137).double(message.minimum);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MedicationProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMedicationProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.activeIngredient = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dosage = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tablets = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.barCode = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.image = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.subcategory = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.stock = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.controlled = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.vat = reader.double();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.antibiotic = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 137) {
            break;
          }

          message.minimum = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MedicationProto {
    return {
      brand: isSet(object.brand) ? globalThis.String(object.brand) : "",
      activeIngredient: isSet(object.activeIngredient)
        ? globalThis.String(object.activeIngredient)
        : isSet(object.active_ingredient)
        ? globalThis.String(object.active_ingredient)
        : "",
      dosage: isSet(object.dosage) ? globalThis.String(object.dosage) : "",
      tablets: isSet(object.tablets) ? globalThis.String(object.tablets) : "",
      barCode: isSet(object.barCode)
        ? globalThis.String(object.barCode)
        : isSet(object.bar_code)
        ? globalThis.String(object.bar_code)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      subcategory: isSet(object.subcategory) ? globalThis.String(object.subcategory) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      stock: isSet(object.stock) ? globalThis.Number(object.stock) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      controlled: isSet(object.controlled) ? globalThis.Boolean(object.controlled) : false,
      vat: isSet(object.vat) ? globalThis.Number(object.vat) : 0,
      antibiotic: isSet(object.antibiotic) ? globalThis.Boolean(object.antibiotic) : false,
      minimum: isSet(object.minimum) ? globalThis.Number(object.minimum) : 0,
    };
  },

  toJSON(message: MedicationProto): unknown {
    const obj: any = {};
    if (message.brand !== "") {
      obj.brand = message.brand;
    }
    if (message.activeIngredient !== "") {
      obj.activeIngredient = message.activeIngredient;
    }
    if (message.dosage !== "") {
      obj.dosage = message.dosage;
    }
    if (message.tablets !== "") {
      obj.tablets = message.tablets;
    }
    if (message.barCode !== "") {
      obj.barCode = message.barCode;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.subcategory !== "") {
      obj.subcategory = message.subcategory;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.quantity !== 0) {
      obj.quantity = message.quantity;
    }
    if (message.stock !== 0) {
      obj.stock = message.stock;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.controlled !== false) {
      obj.controlled = message.controlled;
    }
    if (message.vat !== 0) {
      obj.vat = message.vat;
    }
    if (message.antibiotic !== false) {
      obj.antibiotic = message.antibiotic;
    }
    if (message.minimum !== 0) {
      obj.minimum = message.minimum;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MedicationProto>, I>>(base?: I): MedicationProto {
    return MedicationProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MedicationProto>, I>>(object: I): MedicationProto {
    const message = createBaseMedicationProto();
    message.brand = object.brand ?? "";
    message.activeIngredient = object.activeIngredient ?? "";
    message.dosage = object.dosage ?? "";
    message.tablets = object.tablets ?? "";
    message.barCode = object.barCode ?? "";
    message.name = object.name ?? "";
    message.image = object.image ?? "";
    message.category = object.category ?? "";
    message.subcategory = object.subcategory ?? "";
    message.price = object.price ?? 0;
    message.quantity = object.quantity ?? 0;
    message.stock = object.stock ?? 0;
    message.description = object.description ?? "";
    message.controlled = object.controlled ?? false;
    message.vat = object.vat ?? 0;
    message.antibiotic = object.antibiotic ?? false;
    message.minimum = object.minimum ?? 0;
    return message;
  },
};

function createBaseOrderContactAndItems(): OrderContactAndItems {
  return {
    orderId: "",
    pharmacyId: "",
    clientName: "",
    clientAddress: "",
    clientIdNumber: "",
    clientPhone: "",
    clientEmail: "",
    items: [],
  };
}

export const OrderContactAndItems: MessageFns<OrderContactAndItems> = {
  encode(message: OrderContactAndItems, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.pharmacyId !== "") {
      writer.uint32(18).string(message.pharmacyId);
    }
    if (message.clientName !== "") {
      writer.uint32(26).string(message.clientName);
    }
    if (message.clientAddress !== "") {
      writer.uint32(34).string(message.clientAddress);
    }
    if (message.clientIdNumber !== "") {
      writer.uint32(42).string(message.clientIdNumber);
    }
    if (message.clientPhone !== "") {
      writer.uint32(50).string(message.clientPhone);
    }
    if (message.clientEmail !== "") {
      writer.uint32(58).string(message.clientEmail);
    }
    for (const v of message.items) {
      OrderItem.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderContactAndItems {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderContactAndItems();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pharmacyId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clientName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.clientAddress = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.clientIdNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.clientPhone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.clientEmail = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.items.push(OrderItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderContactAndItems {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      pharmacyId: isSet(object.pharmacyId)
        ? globalThis.String(object.pharmacyId)
        : isSet(object.pharmacy_id)
        ? globalThis.String(object.pharmacy_id)
        : "",
      clientName: isSet(object.clientName)
        ? globalThis.String(object.clientName)
        : isSet(object.client_name)
        ? globalThis.String(object.client_name)
        : "",
      clientAddress: isSet(object.clientAddress)
        ? globalThis.String(object.clientAddress)
        : isSet(object.client_address)
        ? globalThis.String(object.client_address)
        : "",
      clientIdNumber: isSet(object.clientIdNumber)
        ? globalThis.String(object.clientIdNumber)
        : isSet(object.client_id_number)
        ? globalThis.String(object.client_id_number)
        : "",
      clientPhone: isSet(object.clientPhone)
        ? globalThis.String(object.clientPhone)
        : isSet(object.client_phone)
        ? globalThis.String(object.client_phone)
        : "",
      clientEmail: isSet(object.clientEmail)
        ? globalThis.String(object.clientEmail)
        : isSet(object.client_email)
        ? globalThis.String(object.client_email)
        : "",
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => OrderItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OrderContactAndItems): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.pharmacyId !== "") {
      obj.pharmacyId = message.pharmacyId;
    }
    if (message.clientName !== "") {
      obj.clientName = message.clientName;
    }
    if (message.clientAddress !== "") {
      obj.clientAddress = message.clientAddress;
    }
    if (message.clientIdNumber !== "") {
      obj.clientIdNumber = message.clientIdNumber;
    }
    if (message.clientPhone !== "") {
      obj.clientPhone = message.clientPhone;
    }
    if (message.clientEmail !== "") {
      obj.clientEmail = message.clientEmail;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => OrderItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderContactAndItems>, I>>(base?: I): OrderContactAndItems {
    return OrderContactAndItems.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderContactAndItems>, I>>(object: I): OrderContactAndItems {
    const message = createBaseOrderContactAndItems();
    message.orderId = object.orderId ?? "";
    message.pharmacyId = object.pharmacyId ?? "";
    message.clientName = object.clientName ?? "";
    message.clientAddress = object.clientAddress ?? "";
    message.clientIdNumber = object.clientIdNumber ?? "";
    message.clientPhone = object.clientPhone ?? "";
    message.clientEmail = object.clientEmail ?? "";
    message.items = object.items?.map((e) => OrderItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOrderItem(): OrderItem {
  return { barcode: "", quantity: 0 };
}

export const OrderItem: MessageFns<OrderItem> = {
  encode(message: OrderItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.barcode !== "") {
      writer.uint32(10).string(message.barcode);
    }
    if (message.quantity !== 0) {
      writer.uint32(16).int32(message.quantity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.barcode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderItem {
    return {
      barcode: isSet(object.barcode) ? globalThis.String(object.barcode) : "",
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
    };
  },

  toJSON(message: OrderItem): unknown {
    const obj: any = {};
    if (message.barcode !== "") {
      obj.barcode = message.barcode;
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderItem>, I>>(base?: I): OrderItem {
    return OrderItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderItem>, I>>(object: I): OrderItem {
    const message = createBaseOrderItem();
    message.barcode = object.barcode ?? "";
    message.quantity = object.quantity ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
